### ISSUE TITLE
Sentry library dependecy clash when doing `pod install`

### ISSUE THREAD

**Issue by tautvilas** [passbase/rn-passbase#1]
I am using Sentry as a dependency in my project. When installing passbase pods I am getting this error:

```
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In snapshot (Podfile.lock):
    Sentry (= 4.4.0, ~> 4.4.0)

  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 1.1.0, which depends on
      Sentry (~> 4.4.0)

    react-native-passbase (from `../node_modules/@passbase/react-native-passbase`) was resolved to 0.0.11, which depends on
      Passbase (~> 1.7.0) was resolved to 1.7.0, which depends on
        Sentry (~> 4.3.1)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Sentry` inside your development pod `react-native-passbase`.
   You should run `pod update Sentry` to apply changes you've made.
```

Any ideas how this could be solved? Thanks

**Comment by passbase** [comment]
Hi Tautvilas,

Let us quickly have a look into this. Happy to help and provide a fix.

*( http://www.passbase.com/ )

 Mathias J. Klenk* | Co-Founder at P assbase * Email:* mathias@passbase.com | *Mobile:* +1 / 650 440-9293
 *WEBSITE ( http://www.passbase.com/ )  |  BLOG ( https://medium.com/passbase )  |  TWITTER ( https://twitter.com/getpassbase/ )*

**Comment by passbase** [comment]
Hi @tautvilas,

we just pushed an update live, which removes the version requirement for Sentry. Hence it should work now with your existing version. 

**Preparation:**
Please go into your Podfile and ensure those are your top 3 lines (we just updated that): 
`source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/passbase/zoom-cocoapods-specs'
source 'https://github.com/passbase/cocoapods-specs.git'`

**Fix:**
Then cd into your ios folder and run `pod update`. This should download the latest version of the SDK (`1.7.1` as of this writing). Then try to run your App. 

If this doesn't work, try to remove the Pods from your ios project folder with the following commands:
`rm -rf Pods`
`rm -rf Podfile.lock`
`pod cache clean --all`

And run another time `pod update`. This will give you a clean new install of all Pods.

Also, feel free to join our [developer slack](https://join.slack.com/t/passbasesupport/shared_invite/enQtNzE1Njc5ODYzNDczLTEzNWNkODA0OTc4YTBlNDY4M2Q4ZDEyMTRlZjE5YjY2MzBlOWMzY2NhOTYzMmIxMDM5ZmRiYTc4NzdmNDQ5NDE), then we can help you even quicker or debug if there are more issues :)

**Comment by passbase** [comment]
Also, I updated the react-native demo app here, so it worked there: https://github.com/passbase/react-native-demo-app
Let us know if it resolved the issue!

**Comment by tautvilas** [comment]
Hi, thanks for quick response!

pod install now works. However I did not use `use_frameworks!` directive because I get `target has transitive dependencies that include statically linked binaries:` errors on some of my other pods if I do (intercom, google maps). Do I must use the directive?

However after pod install when I compile the project I get `missing required module Sentry` errors

<img width="856" alt="Screenshot 2019-12-19 at 14 29 29" src="https://user-images.githubusercontent.com/1044090/71173801-52409d00-226c-11ea-8823-38a4180ca28f.png">

**Comment by tautvilas** [comment]
After making use_frameworks not mandatory in 0.0.12 this problem is resolved

**Comment by mattk90** [comment]
This problem has been fixed with the latest version which doesn't require `use_frameworks!` anymore.
