### ISSUE TITLE
iOS privacy "Confirm" button and checkbox not operating well

### ISSUE THREAD

**Issue by kgcdream2019** [passbase/rn-passbase#23]
I am using rn-passbase 2.7.1 for my project.
In iOS version,  there are checkbox and "confirm" button in privacy page
This button doesn't operate well.
What is the reason?
 I have 2 phones , one is iPhoneX and another is iPhone6.
it is ok in iPhone6, but there are problem in iPhoneX.

**Comment by skorostetskyi** [comment]
Please update your SDK to the latest 2.12.0 version.
