### ISSUE TITLE
Mistake in build.gradle

### ISSUE THREAD

**Issue by melon-1999** [passbase/rn-passbase#6]
There is a misspelling in the build.gradle file which leads to an error. (line 44: implementation ('com.passbase:passbase_sdk:2.1.7  ') **(2 spaces after the sdk)!**

**Comment by skorostetskyi** [comment]
Thank you @melon-1999 for flagging that.
The fix has been pushed to the repo.
Tomorrow we are going to release a new version `2.1.8` with improved features.
